# Exercise 4.7 Deriving New Variables

### 1. [Import Libraries](#import_libraries)

### 2. [Import Dataframe](#import_dataframe)

### 3. [Create New Column Sorted By Prices](#price_column)

### 4. [If Statments Using loc](#if_loc)

### 5. [For Loops](#for_loops)

### 6. [Create an Hours Category Column](#hours_category)

### Import Libraries
<a id='import_libraries'></a>

In [1]:
import pandas as pd
import numpy as np
import os

### Import Dataframe
<a id='import_dataframe'></a>

In [2]:
path = r"C:\Users\corri\Documents\New Career\Achievment 4\Instacart Basket Analysis\Data"

In [3]:
ords_prds_merged = pd.read_pickle(os.path.join(path, 'Prepared Data', 'orders_products_merged.pkl'))

In [4]:
# Check dataframe
ords_prds_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both

In [5]:
# Drop unnecessary column
ords_prds_merged = ords_prds_merged.drop(columns = ['_merge'])

In [6]:
# Check cleaned dataframe
ords_prds_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0

In [7]:
# Create dataframe subset
df = ords_prds_merged[:1000000]

In [8]:
df.shape

(1000000, 13)

### Create new column sorted by prices
<a id='price_column'></a>

In [9]:
# Create the function
def price_label(row):
    if row ['prices'] <= 5:
        return 'Low-range product'
    elif (row ['prices'] > 5) and (row ['prices'] <= 15):
        return 'Mid-range product'
    elif row ['prices'] > 15:
        return 'High-range product'
    else: return 'Not enough data'

In [10]:
df['price_range'] = df.apply(price_label, axis = 1)

C:\Users\corri\AppData\Local\Temp\ipykernel_13964\935325922.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis = 1)

In [11]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product

In [12]:
df['price_range'].value_counts(dropna = False)

Mid-range product    756450
Low-range product    243550
Name: price_range, dtype: int64

In [13]:
df['prices'].max()

14.8

### If statements using loc
<a id='if_loc'></a>

In [15]:
df.loc[df['prices'] >= 15, 'price_loc'] = 'High-range product'

In [16]:
df.loc[(df['prices'] < 15) & (df['prices'] > 5), 'price_loc'] = 'Mid-range product'

In [17]:
df.loc[df['prices'] <= 5, 'price_loc'] = 'Low-range product'

In [18]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range,price_loc
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Mid-range product
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range product
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range product
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range product
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Mid-range product

In [19]:
df['price_loc'].value_counts(dropna = False)

Mid-range product    756450
Low-range product    243550
Name: price_loc, dtype: int64

In [20]:
ords_prds_merged.loc[ords_prds_merged['prices'] >= 15, 'price_ranges'] = 'High-range product'

In [21]:
ords_prds_merged.loc[(ords_prds_merged['prices'] < 15) & (ords_prds_merged['prices'] > 5), 'price_ranges'] = 'Mid-range product'

In [22]:
ords_prds_merged.loc[(ords_prds_merged['prices'] <= 5), 'price_ranges'] = 'Low-range product'

In [23]:
ords_prds_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_ranges
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product

In [24]:
ords_prds_merged['price_ranges'].value_counts(dropna = False)

Mid-range product     21791748
Low-range product     10126339
High-range product      514943
Name: price_ranges, dtype: int64

### For Loops
<a id='for_loops'></a>

In [26]:
ords_prds_merged['orders_day_of_week'].value_counts(dropna = False)

0    6209410
1    5665604
6    4500101
2    4217610
5    4209334
3    3843929
4    3787042
Name: orders_day_of_week, dtype: int64

In [27]:
result = []
for value in ords_prds_merged['orders_day_of_week']:
    if value == 0:
        result.append("Busiest Day")
    elif value == 4:
        result.append ("Least Busy")
    else:
        result.append("Regularly Busy")

In [28]:
ords_prds_merged['busiest_day'] = result

In [29]:
ords_prds_merged.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_ranges,busiest_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly Busy
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy

In [30]:
ords_prds_merged['busiest_day'].value_counts(dropna = False)

Regularly Busy    22436578
Busiest Day        6209410
Least Busy         3787042
Name: busiest_day, dtype: int64

In [31]:
# Create two busiest days label
busy = []
for value in ords_prds_merged['orders_day_of_week']:
    if value == 0 or value == 1:
        busy.append("Busiest Days")
    elif value == 4 or value == 3:
        busy.append("Slowest Days")
    else:
        busy.append("Regular Day")

In [40]:
busy

['Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Regular Day',
 'Slowest Days',
 'Slowest Days',
 'Slowest Days',
 'Busiest Days',
 'Regular Day',
 'Slowest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Busiest Days',
 'Slowest Days',
 'Busiest Days',
 ...]

In [32]:
ords_prds_merged['shopping_days'] = busy

In [33]:
ords_prds_merged.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_ranges,busiest_day,shopping_days
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly Busy,Regular Day
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Slowest Days
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Slowest Days
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy,Slowest Days
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy,Slowest Days
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Regular Day
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Busiest Days
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Busiest Days
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Busiest Days
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy,Slowest Days

In [34]:
ords_prds_merged['shopping_days'].value_counts(dropna = False)

Regular Day     12927045
Busiest Days    11875014
Slowest Days     7630971
Name: shopping_days, dtype: int64

#### The total count of days are the same with a shift to fewer in the regular day category.  The slowest days category doubled.

### Create an hours category column
<a id='hours_category'></a>

In [35]:
ords_prds_merged['order_hour_of_day'].value_counts(dropna = False)

10    2764288
11    2738483
14    2691448
15    2664420
13    2663169
12    2620719
16    2537358
9     2456591
17    2089385
8     1719888
18    1637858
19    1259335
20     976991
7      891900
21     796341
22     634715
23     402593
6      290763
0      218925
1      115780
5       88054
2       69429
4       53280
3       51317
Name: order_hour_of_day, dtype: int64

#### I will divide the hours into most (7 digit count), average (6 digit count) and fewest (5 digit count) number of orders.

In [60]:
time = []
for value in ords_prds_merged['order_hour_of_day']:
    if value in {10,11,14,15,13,12,16,9,17,8,18,19}:
        time.append("Most orders")
    elif value in {20,7,21,22,23,6,0,1}:
        time.append("Average orders")
    elif value in {5,2,4,3}:
        time.append("Fewest orders")

In [61]:
time

['Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 ...]

In [62]:
ords_prds_merged['busy_hours'] = time

In [63]:
ords_prds_merged.head(10)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_ranges,busiest_day,shopping_days,busy_hours
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly Busy,Regular Day,Most orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Slowest Days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Slowest Days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy,Slowest Days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy,Slowest Days,Most orders
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Regular Day,Average orders
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Busiest Days,Most orders
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Busiest Days,Most orders
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly Busy,Busiest Days,Most orders
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least Busy,Slowest Days,Most orders

In [64]:
ords_prds_merged['busy_hours'].value_counts(dropna = False)

Most orders       27842942
Average orders     4328008
Fewest orders       262080
Name: busy_hours, dtype: int64

In [65]:
ords_prds_merged.to_pickle(os.path.join(path, 'Prepared Data', 'derived_orders_products.pkl'))